// <auto-generated />
using ColorGlyphs.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ColorGlyphs.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260508231836_SemillaDrawingModesLimpia")]
    partial class SemillaDrawingModesLimpia
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("ColorGlyphs.Models.FormModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Forms");
                });

            modelBuilder.Entity("ColorGlyphs.Models.GlyphColorModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Colours");
                });

            modelBuilder.Entity("ColorGlyphs.Models.GlyphForm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FormId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GlyphId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FormId");

                    b.HasIndex("GlyphId");

                    b.ToTable("GlyphForms");
                });

            modelBuilder.Entity("ColorGlyphs.Models.GlyphModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Caracter")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Colores")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DrawingModeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DrawingModeId");

                    b.ToTable("Glyphs");
                });

            modelBuilder.Entity("DrawingMode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DrawingModes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Clásico"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Élfico"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Rúnico"
                        });
                });

            modelBuilder.Entity("ColorGlyphs.Models.GlyphForm", b =>
                {
                    b.HasOne("ColorGlyphs.Models.FormModel", "Form")
                        .WithMany()
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ColorGlyphs.Models.GlyphModel", "Glyph")
                        .WithMany("GlyphForms")
                        .HasForeignKey("GlyphId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Form");

                    b.Navigation("Glyph");
                });

            modelBuilder.Entity("ColorGlyphs.Models.GlyphModel", b =>
                {
                    b.HasOne("DrawingMode", "DrawingMode")
                        .WithMany("Glyphs")
                        .HasForeignKey("DrawingModeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DrawingMode");
                });

            modelBuilder.Entity("ColorGlyphs.Models.GlyphModel", b =>
                {
                    b.Navigation("GlyphForms");
                });

            modelBuilder.Entity("DrawingMode", b =>
                {
                    b.Navigation("Glyphs");
                });
#pragma warning restore 612, 618
        }
    }
}
