// <auto-generated />
using ColorGlyphs.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ColorGlyphs.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("ColorGlyphs.Models.Cuadricula", b =>
                {
                    b.Property<char>("Letra")
                        .HasColumnType("TEXT");

                    b.Property<string>("ColoresSerializados")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Forma")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Letra");

                    b.ToTable("Cuadriculas");
                });
#pragma warning restore 612, 618
        }
    }
}
